[package]
name = "iced_aw"
version = "0.7.0"
authors = [
    "Kaiden42 <gitlab@tinysn.com>",
    "Andrew Wheeler <genusistimelord@gmail.com>",
]
edition = "2021"
description = "Additional widgets for the Iced GUI library"
license = "MIT"
repository = "https://github.com/iced-rs/iced_aw"
# TODO documentation
readme = "README.md"
keywords = ["gui", "graphics", "interface", "widgets", "iced"]
categories = ["gui"]

[features]
badge = []
card = []
date_picker = ["chrono", "once_cell", "icons"]
color_picker = ["icons", "iced_widget/canvas"]
cupertino = ["iced_widget/canvas", "time"]
floating_element = []
grid = ["itertools"]
glow = []                                               # TODO
icons = []
modal = []
tab_bar = []
tabs = ["tab_bar"]
time_picker = ["chrono", "icons", "iced_widget/canvas"]
wrap = []
number_input = ["num-traits"]
selection_list = []
split = []
menu = []
quad = []
spinner = []
context_menu = []
segmented_button = []
slide_bar = []

default = [
    "badge",
    "card",
    "number_input",
    "date_picker",
    "color_picker",
    "floating_element",
    "grid",
    "modal",
    "tab_bar",
    "tabs",
    "time_picker",
    "slide_bar",
    "wrap",
    "selection_list",
    "split",
    "quad",
    "context_menu",
    "spinner",
    "cupertino",
    "segmented_button",
    #"menu",
]

[dependencies]
cfg-if = "1.0"
num-traits = { version = "0.2.16", optional = true }
time = { version = "0.3.23", features = ["local-offset"], optional = true }
chrono = { version = "0.4.26", optional = true }
once_cell = { version = "1.18.0", optional = true }
itertools = { version = "0.11.0", optional = true }


[dependencies.iced_widget]
git = "https://github.com/Davidster/iced.git"
branch = "master"

[profile.dev.package."*"]
opt-level = 2

[workspace]
members = [
    "examples/badge",
    "examples/card",
    "examples/number_input",
    "examples/date_picker",
    "examples/color_picker",
    "examples/floating_element",
    "examples/floating_element_anchors",
    "examples/grid",
    "examples/modal",
    "examples/modal_component",
    "examples/multiple_modals",
    "examples/tab_bar",
    "examples/tabs",
    "examples/time_picker",
    "examples/sliderbar",
    "examples/wrap",
    "examples/selection_list",
    "examples/split",
    "examples/split_scroller",
    "examples/context_menu",
    "examples/spinner",
    "examples/cupertino/cupertino_button",
    "examples/cupertino/cupertino_spinner",
    "examples/cupertino/cupertino_switch",
    "examples/WidgetIDReturn",
    "examples/segmented_button",
    #"examples/menu",
]

[workspace.dependencies.iced]
git = "https://github.com/Davidster/iced.git"
branch = "master"
features = ["advanced", "lazy", "tokio"]

[workspace.dependencies.iced_aw]
path = "./"
default-features = false
features = ["num-traits"]
